# Generated by Django 6.0.1 on 2026-01-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategorizeQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
            ],
            options={
                'db_table': 'quiz_categorize_question',
            },
        ),
        migrations.CreateModel(
            name='QuizCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'quiz_category',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
            ],
            options={
                'db_table': 'quiz_question_type',
            },
        ),
        migrations.CreateModel(
            name='QuizCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorizequestionmodel')),
            ],
            options={
                'db_table': 'quiz_categorize_group',
            },
        ),
        migrations.CreateModel(
            name='QuizCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorygroup')),
            ],
            options={
                'db_table': 'quiz_categorize_item',
            },
        ),
        migrations.AddField(
            model_name='quizcategorizequestionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel'),
        ),
        migrations.CreateModel(
            name='QuizGapFillMultipleChoiceQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_gap_fill_multiple_choice_question',
            },
        ),
        migrations.CreateModel(
            name='QuizGapFillQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_gap_fill_question',
            },
        ),
        migrations.CreateModel(
            name='QuizGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizgapfillquestionmodel')),
            ],
            options={
                'db_table': 'quiz_gap',
            },
        ),
        migrations.CreateModel(
            name='QuizGapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('gap', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizgap')),
            ],
            options={
                'db_table': 'quiz_gap_item',
            },
        ),
        migrations.CreateModel(
            name='QuizGapMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizgapfillmultiplechoicequestionmodel')),
            ],
            options={
                'db_table': 'quiz_gap_multiple_choice',
            },
        ),
        migrations.CreateModel(
            name='QuizGapChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizgapmultiplechoice')),
            ],
            options={
                'db_table': 'quiz_gap_choice_item',
            },
        ),
        migrations.CreateModel(
            name='QuizMappingQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_mapping_question',
            },
        ),
        migrations.CreateModel(
            name='QuizMappingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('column_name', models.TextField(blank=True, null=True)),
                ('pair', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizmappingitem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizmappingquestionmodel')),
            ],
            options={
                'db_table': 'quiz_mapping_item',
            },
        ),
        migrations.CreateModel(
            name='QuizMultipleChoiceQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_multiple_question',
            },
        ),
        migrations.CreateModel(
            name='QuizMultipleChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizmultiplechoicequestionmodel')),
            ],
            options={
                'db_table': 'quiz_multiple_choice_item',
            },
        ),
        migrations.AddField(
            model_name='quizcategorizequestionmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel'),
        ),
        migrations.CreateModel(
            name='QuizRecallQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('min_correct_answers', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_recall_question',
            },
        ),
        migrations.CreateModel(
            name='QuizRecallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizrecallquestionmodel')),
            ],
            options={
                'db_table': 'quiz_recall_item',
            },
        ),
        migrations.CreateModel(
            name='QuizTrueFalseQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('context', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizcategorymodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quizquestiontypemodel')),
            ],
            options={
                'db_table': 'quiz_true_false_question',
            },
        ),
        migrations.CreateModel(
            name='QuizTrueFalseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.quiztruefalsequestionmodel')),
            ],
            options={
                'db_table': 'quiz_true_false_item',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('half', models.PositiveSmallIntegerField(choices=[(0, 'First half'), (1, 'Second half')])),
            ],
            options={
                'db_table': 'semester',
                'ordering': ['-year', '-half'],
                'unique_together': {('year', 'half')},
            },
        ),
        migrations.AddField(
            model_name='quiztruefalsequestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizrecallquestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizmultiplechoicequestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizmappingquestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizgapfillquestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizgapfillmultiplechoicequestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
        migrations.AddField(
            model_name='quizcategorizequestionmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='open_ithageneia.semester'),
        ),
    ]
