services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS
      - IS_PREVIEW_DEPLOYMENT
      - PREVIEW_SUPERUSER_USERNAME
      - PREVIEW_SUPERUSER_PASSWORD
    volumes:
      - static_data:/code/static
      - media_data:/code/media
      - db_data:/code/db
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - static_data:/var/www/static:ro
      - media_data:/var/www/media:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-ithageneia-http.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.open-ithageneia-http.entrypoints=http
      - traefik.http.routers.open-ithageneia-https.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.open-ithageneia-https.entrypoints=https
      - traefik.http.routers.open-ithageneia-https.tls=true
      - traefik.http.routers.open-ithageneia-https.tls.certresolver=letsencrypt
      - traefik.http.services.open-ithageneia.loadbalancer.server.port=8080

volumes:
  static_data:
  media_data:
  # We keep the same volume name we had before to not recreate the db from scratch
  db_data:
    name: ow44occokc4kswcgc8ks0gwc-ow44occokc4kswcgc8ks0gwc-open_ithageneia_db
