# Generated by Django 6.0.1 on 2026-02-02 13:30

import django.core.validators
import django.db.models.deletion
import django_jsonform.models.fields
import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to=quiz.models.get_quiz_asset_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='quiz_examse_year_d8e3a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uniq_exam_session'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='month_between_1_and_12')],
            },
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('TRUE_FALSE', 'True/False'), ('MULTIPLE_CHOICE', 'Mutliple Choice')], default='TRUE_FALSE', max_length=15)),
                ('category', models.CharField(choices=[('GEORGRAPHY', 'Geography'), ('CIVICS', 'Civics'), ('HISTORY', 'History'), ('CULTURE', 'Culture')], default='GEORGRAPHY', max_length=10)),
                ('instructions', models.TextField(blank=True, default='Γράψτε στο τετράδιό σας τον αριθμό του θέματος και τον αριθμό της κάθε πρότασης, σημειώνοντας Σ, αν η πρόταση που σας δίνεται παρακάτω είναι σωστή, ή Λ, αν είναι λάθος.')),
                ('content', django_jsonform.models.fields.JSONField(blank=True, default=quiz.models.default_quiz_content)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='quiz.examsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
