# Generated by Django 6.0.1 on 2026-03-25 23:40

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="OpenEnded",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("is_active", models.BooleanField(default=True)),
				(
					"category",
					models.CharField(
						choices=[
							("GEOGRAPHY", "Geography"),
							("CIVICS", "Civics"),
							("HISTORY", "History"),
							("CULTURE", "Culture"),
						],
						default="GEOGRAPHY",
						max_length=9,
					),
				),
				(
					"content",
					django_jsonform.models.fields.JSONField(blank=True, default=dict),
				),
				(
					"exam_sessions",
					models.ManyToManyField(
						blank=True,
						related_name="%(class)s_quizzes",
						to="quiz.examsession",
					),
				),
			],
			options={
				"verbose_name_plural": "Open Ended",
			},
		),
	]
