# Generated by Django 6.0.1 on 2026-07-23 10:27

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0004_matching_content_list_to_object"),
	]

	operations = [
		migrations.AlterField(
			model_name="matching",
			name="content",
			field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
		),
		migrations.CreateModel(
			name="MapPointer",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("is_active", models.BooleanField(default=True)),
				(
					"category",
					models.CharField(
						choices=[
							("GEOGRAPHY", "Geography"),
							("CIVICS", "Civics"),
							("HISTORY", "History"),
							("CULTURE", "Culture"),
						],
						default="GEOGRAPHY",
						max_length=9,
					),
				),
				(
					"level",
					models.PositiveSmallIntegerField(
						choices=[
							(1, "Geographic department (Γεωγραφικό διαμέρισμα)"),
							(2, "Region (Περιφέρεια)"),
							(3, "Prefecture unit (Νομός / Νησί)"),
							(4, "Municipality (Δήμος)"),
						],
						default=4,
						help_text="Administrative division level used for the map.",
					),
				),
				(
					"content",
					django_jsonform.models.fields.JSONField(blank=True, default=dict),
				),
				(
					"exam_sessions",
					models.ManyToManyField(
						blank=True,
						related_name="%(class)s_quizzes",
						to="quiz.examsession",
					),
				),
			],
			options={
				"verbose_name_plural": "Map Pointer",
			},
		),
	]
