# Generated by Django 6.0.1 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0005_alter_matching_content_mappointer"),
	]

	operations = [
		migrations.AlterField(
			model_name="mappointer",
			name="level",
			field=models.PositiveSmallIntegerField(
				choices=[
					(1, "Decentralized administration (Αποκεντρωμένη διοίκηση)"),
					(2, "Region (Περιφέρεια)"),
					(3, "Prefecture unit (Νομός / Νησί)"),
					(4, "Municipality (Δήμος)"),
					(5, "Geographic department (Γεωγραφικό διαμέρισμα)"),
				],
				default=4,
				help_text="Administrative division level used for the map.",
			),
		),
	]
