# Generated by Django 6.0.1 on 2026-07-26 11:41

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0006_alter_mappointer_level"),
	]

	operations = [
		migrations.AddField(
			model_name="quizasset",
			name="audio",
			field=models.FileField(
				blank=True, null=True, upload_to=quiz.models.get_quiz_asset_upload_to
			),
		),
		migrations.AlterField(
			model_name="quizasset",
			name="image",
			field=models.ImageField(
				blank=True, null=True, upload_to=quiz.models.get_quiz_asset_upload_to
			),
		),
	]
