# Generated by Django 6.0.1 on 2026-07-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0007_quizasset_audio_alter_quizasset_image"),
	]

	operations = [
		migrations.AddField(
			model_name="statement",
			name="second_part",
			field=models.OneToOneField(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="first_part",
				to="quiz.statement",
			),
		),
	]
