# Generated by Django 6.0.1 on 2026-07-26 16:17

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0008_statement_second_part"),
	]

	operations = [
		migrations.RemoveIndex(
			model_name="examsession",
			name="quiz_examse_year_d8e3a8_idx",
		),
		migrations.RemoveConstraint(
			model_name="examsession",
			name="uniq_exam_session",
		),
		migrations.RemoveConstraint(
			model_name="examsession",
			name="month_between_1_and_12",
		),
		migrations.RemoveField(
			model_name="statement",
			name="exam_sessions",
		),
		migrations.RemoveField(
			model_name="fillintheblank",
			name="exam_sessions",
		),
		migrations.RemoveField(
			model_name="matching",
			name="exam_sessions",
		),
		migrations.RemoveField(
			model_name="mappointer",
			name="exam_sessions",
		),
		migrations.RemoveField(
			model_name="openended",
			name="exam_sessions",
		),
		migrations.RemoveField(
			model_name="draganddrop",
			name="exam_sessions",
		),
		migrations.DeleteModel(
			name="ExamSession",
		),
	]
