# Generated by Django 6.0.1 on 2026-07-26 16:38

import django.db.models.deletion
from django.db import migrations, models


# Categories previously defined by the ``AbstractQuiz.QuizCategory`` TextChoices,
# in the same order they were declared. The ``code`` matches the value already
# stored in every quiz table's ``category`` column, so existing rows keep
# pointing at the right category once the FK constraint is applied.
DEFAULT_CATEGORIES = [
	("GEOGRAPHY", "Geography", 1),
	("CIVICS", "Civics", 2),
	("HISTORY", "History", 3),
	("CULTURE", "Culture", 4),
]


def seed_categories(apps, schema_editor):
	QuizCategory = apps.get_model("quiz", "QuizCategory")
	QuizCategory.objects.bulk_create(
		[
			QuizCategory(code=code, name=name, order=order)
			for code, name, order in DEFAULT_CATEGORIES
		],
		ignore_conflicts=True,
	)


def unseed_categories(apps, schema_editor):
	QuizCategory = apps.get_model("quiz", "QuizCategory")
	QuizCategory.objects.filter(
		code__in=[code for code, *_ in DEFAULT_CATEGORIES]
	).delete()


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0009_remove_examsession_quiz_examse_year_d8e3a8_idx_and_more"),
	]

	operations = [
		migrations.CreateModel(
			name="QuizCategory",
			fields=[
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"code",
					models.CharField(max_length=32, primary_key=True, serialize=False),
				),
				("name", models.CharField(max_length=64)),
				("order", models.PositiveSmallIntegerField(default=0)),
			],
			options={
				"verbose_name_plural": "Quiz Categories",
				"ordering": ["order", "code"],
			},
		),
		migrations.RunPython(seed_categories, unseed_categories),
		migrations.AlterField(
			model_name="draganddrop",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
		migrations.AlterField(
			model_name="fillintheblank",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
		migrations.AlterField(
			model_name="mappointer",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
		migrations.AlterField(
			model_name="matching",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
		migrations.AlterField(
			model_name="openended",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
		migrations.AlterField(
			model_name="statement",
			name="category",
			field=models.ForeignKey(
				db_column="category",
				default="GEOGRAPHY",
				on_delete=django.db.models.deletion.PROTECT,
				related_name="%(class)ss",
				to="quiz.quizcategory",
			),
		),
	]
