# Generated by Django 6.0.1 on 2026-07-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0010_quizcategory_alter_draganddrop_category_and_more"),
	]

	operations = [
		migrations.RemoveField(
			model_name="statement",
			name="second_part",
		),
		migrations.AddField(
			model_name="statement",
			name="order",
			field=models.PositiveSmallIntegerField(
				default=0, help_text="Display order within a listening question."
			),
		),
		migrations.CreateModel(
			name="Listening",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("is_active", models.BooleanField(default=True)),
				(
					"max_plays",
					models.PositiveSmallIntegerField(
						default=2,
						help_text="How many times the candidate may play the clip.",
					),
				),
				(
					"transcript",
					models.TextField(
						blank=True,
						default="",
						help_text="Optional text of the clip, for review after answering.",
					),
				),
				(
					"audio",
					models.ForeignKey(
						help_text="Quiz asset holding the audio clip.",
						on_delete=django.db.models.deletion.PROTECT,
						related_name="listening_questions",
						to="quiz.quizasset",
					),
				),
				(
					"category",
					models.ForeignKey(
						db_column="category",
						default="GEOGRAPHY",
						on_delete=django.db.models.deletion.PROTECT,
						related_name="%(class)ss",
						to="quiz.quizcategory",
					),
				),
			],
			options={
				"verbose_name_plural": "Listening",
			},
		),
		migrations.AddField(
			model_name="statement",
			name="listening",
			field=models.ForeignKey(
				blank=True,
				help_text="Set when this statement is one part of a listening question.",
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="questions",
				to="quiz.listening",
			),
		),
	]
