# Generated by Django 6.0.1 on 2026-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("quiz", "0011_remove_statement_second_part_statement_order_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="statement",
			name="part",
			field=models.CharField(
				choices=[("A", "Part A"), ("B", "Part B")],
				default="A",
				help_text="Which section of a listening question this belongs to.",
				max_length=1,
			),
		),
		migrations.AlterField(
			model_name="statement",
			name="order",
			field=models.PositiveSmallIntegerField(
				default=0,
				help_text="Display order within its part of a listening question.",
			),
		),
	]
