# Generated by Django 6.0.1 on 2026-09-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_draganddrop_test_number_fillintheblank_test_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='The literal text of this run. Empty for a blank.')),
                ('is_blank', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fill in the blank part',
                'verbose_name_plural': 'Fill in the blank parts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Statements (True/False or Multiple choice)'},
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='left_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='right_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fillintheblank',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='fillintheblank',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='fillintheblank',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fillintheblank',
            name='show_answers_as_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listening',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='listening',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='listening',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mappointer',
            name='min_correct_answers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mappointer',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='mappointer',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='mappointer',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mappointer',
            name='show_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matching',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='matching',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='matching',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='openended',
            name='min_correct_answers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='openended',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='openended',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='openended',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='prompt_audio',
            field=models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='statement',
            name='prompt_image',
            field=models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset'),
        ),
        migrations.AddField(
            model_name='statement',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draganddrop',
            name='content',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='content',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='content',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='matching',
            name='content',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='openended',
            name='content',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='statement',
            name='content',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='DragAndDropValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='quiz.draganddrop')),
            ],
            options={
                'verbose_name': 'Drag and drop value',
                'verbose_name_plural': 'Drag and drop values',
                'ordering': ['side', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FillInTheBlankExtraChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_choices', to='quiz.fillintheblank')),
            ],
            options={
                'verbose_name': 'Fill in the blank extra choice',
                'verbose_name_plural': 'Fill in the blank extra choices',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FillInTheBlankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.fillintheblankpart')),
            ],
            options={
                'verbose_name': 'Fill in the blank choice',
                'verbose_name_plural': 'Fill in the blank choices',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FillInTheBlankText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Use <{{answer}}*> for a blank and mark the correct choice with *. E.g. "Η Κως συνορεύει με <{{την Τουρκία}}*>".')),
                ('has_multiple_choices', models.BooleanField(default=False, editable=False, help_text="Derived: whether any of this sentence's blanks offers a choice.")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='quiz.fillintheblank')),
            ],
            options={
                'verbose_name': 'Fill in the blank text',
                'verbose_name_plural': 'Fill in the blank texts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fillintheblankpart',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quiz.fillintheblanktext'),
        ),
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Decentralized administration (Αποκεντρωμένη διοίκηση)'), (2, 'Region (Περιφέρεια)'), (3, 'Prefecture unit (Νομός / Νησί)'), (4, 'Municipality and islands (Δήμος και νησιά)'), (5, 'Geographic department (Γεωγραφικό διαμέρισμα)')])),
                ('name', models.CharField(help_text='Greek name, exactly as it appears in the GeoJSON.', max_length=255)),
                ('search_name', models.CharField(db_index=True, editable=False, help_text='Accent-folded, casefolded form of the name, for the picker.', max_length=255)),
            ],
            options={
                'verbose_name': 'Map area',
                'verbose_name_plural': 'Map areas',
                'ordering': ['level', 'name'],
                'constraints': [models.UniqueConstraint(fields=('level', 'name'), name='unique_map_area_per_level')],
            },
        ),
        migrations.CreateModel(
            name='MapPointerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.mappointer')),
            ],
            options={
                'verbose_name': 'Map pointer answer',
                'verbose_name_plural': 'Map pointer answers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapPointerAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='quiz.mappointeranswer')),
            ],
            options={
                'verbose_name': 'Map pointer alternative',
                'verbose_name_plural': 'Map pointer alternatives',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapPointerAnswerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_links', to='quiz.mappointeranswer')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_links', to='quiz.maparea')),
            ],
            options={
                'verbose_name': 'Map pointer answer area',
                'verbose_name_plural': 'Map pointer answer areas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(blank=True, default='')),
                ('right_text', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position of the left item in its column.')),
                ('right_order', models.PositiveSmallIntegerField(default=0, help_text='Position of the right item in its column. Leave equal to the left order unless the right column should be shuffled.')),
                ('left_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='quiz.matching')),
                ('right_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset')),
            ],
            options={
                'verbose_name': 'Match pair',
                'verbose_name_plural': 'Match pairs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpenEndedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.openended')),
            ],
            options={
                'verbose_name': 'Open ended answer',
                'verbose_name_plural': 'Open ended answers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpenEndedAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='quiz.openendedanswer')),
            ],
            options={
                'verbose_name': 'Open ended alternative',
                'verbose_name_plural': 'Open ended alternatives',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.statement')),
            ],
            options={
                'verbose_name': 'Statement choice',
                'verbose_name_plural': 'Statement choices',
                'ordering': ['order', 'id'],
            },
        ),
    ]
