# Generated by Django 6.0.1 on 2026-10-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_drop_legacy_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_number', models.SmallIntegerField(blank=True, default=0)),
                ('question_number', models.SmallIntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('SYNONYM', 'Synonym'), ('ANTONYM', 'Antonym')], default='SYNONYM', max_length=15)),
                ('prompt_text', models.TextField(help_text='The sentence, with the word or phrase to underline in curly braces, e.g. «Η τιμή του εισιτηρίου ήταν {προσιτή}.»', verbose_name='sentence')),
                ('category', models.ForeignKey(db_column='category', default='GEOGRAPHY', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='quiz.quizcategory')),
                ('prompt_audio', models.ForeignKey(blank=True, help_text='Audio clip played with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset')),
                ('prompt_image', models.ForeignKey(blank=True, help_text='Image shown with the question.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizasset')),
            ],
            options={
                'verbose_name_plural': 'Word relations (Synonyms/Antonyms)',
            },
        ),
        migrations.CreateModel(
            name='WordRelationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.wordrelation')),
            ],
            options={
                'verbose_name': 'Word relation choice',
                'verbose_name_plural': 'Word relation choices',
                'ordering': ['order', 'id'],
            },
        ),
    ]
